## Робота з бібліотекою Numpy

In [2]:
def homework(message):
    print("\n>>>>>", message, "\n")
import numpy as np
temperature = [20.1, 20.1, 20.2, 20.4]
print(temperature)

t1 = temperature * 5

print(f"При множенні на 5 маємо: {t1}")
homework("Чому маємо такий результат? Тому що операція множення списку на число просто повторює кожен елемент списку задану кількість разів і повертає новий список. ")

t1 = [ x*5 for x in temperature] 
print(f"Тепер отримаємо: {t1}") 
homework("Чому тепер множення успішне? Тому що ми просто повторюємо весь список задану кількість разів, отримуючи новий список, що містить копії початкового списку")
t2 = np.array(temperature)
print("Масив з використанням методів NumPy", t2)

t3 = t2 * 5
print("При множенні на 5 отримуємо:", t3)

[20.1, 20.1, 20.2, 20.4]
При множенні на 5 маємо: [20.1, 20.1, 20.2, 20.4, 20.1, 20.1, 20.2, 20.4, 20.1, 20.1, 20.2, 20.4, 20.1, 20.1, 20.2, 20.4, 20.1, 20.1, 20.2, 20.4]

>>>>> Чому маємо такий результат? Тому що операція множення списку на число просто повторює кожен елемент списку задану кількість разів і повертає новий список.  

Тепер отримаємо: [100.5, 100.5, 101.0, 102.0]

>>>>> Чому тепер множення успішне? Тому що ми просто повторюємо весь список задану кількість разів, отримуючи новий список, що містить копії початкового списку 

Масив з використанням методів NumPy [20.1 20.1 20.2 20.4]
При множенні на 5 отримуємо: [100.5 100.5 101.  102. ]


## Вектори, створення та робота з ними

In [3]:
print("Все можна сторити ручну за допомогою методу np.array передавши йому набір значень у вигляді List:")
vector_row = np.array([[1, -5, 3, 2, 4]])
vector_column = np.array([[1], 
                          [2], 
                          [3], 
                          [4]])
print(vector_row, "\nВектор має розмір", vector_row.shape)
print(vector_column, "\nВектор має розмір", vector_column.shape)

Все можна сторити ручну за допомогою методу np.array передавши йому набір значень у вигляді List:
[[ 1 -5  3  2  4]] 
Вектор має розмір (1, 5)
[[1]
 [2]
 [3]
 [4]] 
Вектор має розмір (4, 1)


### Метод arange - генерує послідовність чисел з певним кроком у заданому інтервалі

In [4]:
start = 5
size_of_vec = 100
x = range(size_of_vec)
a = np.arange(size_of_vec)
print(f"Масив згенерований простим range: {x[0:5]} та методом arange: {a[0:5]}")
homework("Виведіть весь діапазон чисел.")

size_of_vec = 100
x = range(size_of_vec)
a = np.arange(size_of_vec)
print(f"Масив згенерований простим range: {list(x)} та методом arange: {list(a)}")

Масив згенерований простим range: range(0, 5) та методом arange: [0 1 2 3 4]

>>>>> Виведіть весь діапазон чисел. 

Масив згенерований простим range: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99] та методом arange: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]


In [7]:
a = np.arange(start, size_of_vec)
print(f"Можемо задавати початок генерації вектора, перший елемент: {a[0]}")
homework("Виведіть якесь число з середини діапазону.")
start = 1
size_of_vec = 76
a = np.arange(start, size_of_vec)
print(a)

x = range(start, size_of_vec)
print("Те саме але з вбудованою функцією range:", x)
print("Власне вивід значень:", list(x)[0], )

x = range(start, size_of_vec)
mid = len(x) // 2
print(f"Середина діапазону: {x[mid]}")

Можемо задавати початок генерації вектора, перший елемент: 4

>>>>> Виведіть якесь число з середини діапазону. 

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75]
Те саме але з вбудованою функцією range: range(1, 76)
Власне вивід значень: 1
Середина діапазону: 38


In [8]:
x = np.arange(0.04, 1.84, 0.08)
print("З кроком 0.08:", x, "\n Зерніть уагу на заокруглення")
homework("Згенеруйте значення де крок буде мати чотири нулі після коми, яким буде результат?")

x = np.arange(0.04, 1.84, 0.0001)
print(x)

З кроком 0.08: [0.04 0.12 0.2  0.28 0.36 0.44 0.52 0.6  0.68 0.76 0.84 0.92 1.   1.08
 1.16 1.24 1.32 1.4  1.48 1.56 1.64 1.72 1.8 ] 
 Зерніть уагу на заокруглення

>>>>> Згенеруйте значення де крок буде мати чотири нулі після коми, яким буде результат? 

[0.04   0.0401 0.0402 ... 1.8397 1.8398 1.8399]


In [9]:
y = x * 2.5
print("Після перемноження:", y)
homework("Піднесіть отримане число до степеня та поділіть на 0.4 - Яким буде результат?")

a = y ** 2 / 0.4
print("Після піднесення до степеня та ділення на 0.4:", a)

Після перемноження: [0.1     0.10025 0.1005  ... 4.59925 4.5995  4.59975]

>>>>> Піднесіть отримане число до степеня та поділіть на 0.4 - Яким буде результат? 

Після піднесення до степеня та ділення на 0.4: [2.50000000e-02 2.51251563e-02 2.52506250e-02 ... 5.28827514e+01
 5.28885006e+01 5.28942502e+01]


### Метод linspace - генерує задану кількістю чисел у певному діапазоні, 50 чисел за замовчуванням

In [10]:
a = np.linspace(start, size_of_vec)
print(f"Згенерували {len(a)} чисел в діапазоні {a[0]} до {a[-1]}")
#print(f"Власне числа: {a}")
homework("Виведіть кожне друге число згенерованого діапазону. Тут буде потрібен цикл :)")

for i in range(len(a)):
    if i % 2 == 0:
        print(a[i])

Згенерували 50 чисел в діапазоні 1.0 до 76.0

>>>>> Виведіть кожне друге число згенерованого діапазону. Тут буде потрібен цикл :) 

1.0
4.061224489795919
7.122448979591836
10.183673469387754
13.244897959183673
16.306122448979593
19.36734693877551
22.428571428571427
25.489795918367346
28.551020408163264
31.612244897959183
34.6734693877551
37.73469387755102
40.795918367346935
43.857142857142854
46.91836734693877
49.97959183673469
53.04081632653061
56.10204081632653
59.16326530612245
62.224489795918366
65.28571428571428
68.3469387755102
71.40816326530611
74.46938775510203


In [11]:
print("Можна зменшити кількість чисел до 5:")
a = np.linspace(start, size_of_vec, 5)
print(a)
homework("Збільшіть кількість чисел до 100. Виведіть перших та останніх 10.")

a = np.linspace(start, size_of_vec, 100)
print(f"Згенерували {len(a)} чисел в діапазоні {a[0]} до {a[-1]}")
print(f"Перші 10 чисел: {a[:10]}")
print(f"Останні 10 чисел: {a[-10:]}")

Можна зменшити кількість чисел до 5:
[ 1.   19.75 38.5  57.25 76.  ]

>>>>> Збільшіть кількість чисел до 100. Виведіть перших та останніх 10. 

Згенерували 100 чисел в діапазоні 1.0 до 76.0
Перші 10 чисел: [1.         1.75757576 2.51515152 3.27272727 4.03030303 4.78787879
 5.54545455 6.3030303  7.06060606 7.81818182]
Останні 10 чисел: [69.18181818 69.93939394 70.6969697  71.45454545 72.21212121 72.96969697
 73.72727273 74.48484848 75.24242424 76.        ]


In [ ]:
print("""Як бачимо перше та останнє значення завжди входять у згенерований діапазон. 
Відповідно при цьому вираховується крок.
Це можна змінити, виключивши останнє значення з визначення діапазону.
""")

print(np.linspace(start, size_of_vec, 5, endpoint=False))
homework("Спробуйте самі порахуавти крок.")

-------

_, sp_1 = np.linspace(start, size_of_vec, 5, endpoint=True, retstep=True)
_, sp_2 = np.linspace(start, size_of_vec, 5, endpoint=False, retstep=True)
print(f"Для порівняння, ми можемо визначити крок автоматично, у нашому випадку це {sp_1} та {sp_2}")
homework("Чому маємо такий крок?")

-------

### Типи масивів/векторів

In [12]:
examples = {
    'Скаляр': np.array(1), 
    'Вектор Рядок': np.array([1, 2, 3]), 
    'Вектор Стовпець': np.array([[1], [2], [3]]), 
    'Матриця': np.array([[1, 2],[3, 4], [5, 6]]),
    'Багатовимірна Матриця': np.array([ [[111, 112], [121, 122]],
                                        [[211, 212], [221, 222]],
                                        [[311, 312], [321, 322]] ])
    }
for key in examples:
    print(f"Розглядаємо приклад з {key}. \nЗначення x буде: \n", examples[key])
    print(f"Тип {key} x: ", type(examples[key]))
    print(f"Розмірність/вимір {key} x:", np.ndim(examples[key]))
    print(f"Форма {key} x: ", examples[key].shape)
    print(f"Кількість елементів х: {np.size(examples[key])}")
    print("-=-"*10)

homework("""Як Ви думаєте чому маємо такий результат для функції np.ndim (Розмірність/вимір/dimension).
Чому значення для векторів та матриць однакове та не співпдає з значенням shape?
Задайте власні вектори з різними числами.""")

homework("Функція np.ndim повертає кількість вимірів (розмірностей) масиву, а shape повертає кортеж, що містить розміри кожного з вимірів масиву. Вектори") 


Розглядаємо приклад з Скаляр. 
Значення x буде: 
 1
Тип Скаляр x:  <class 'numpy.ndarray'>
Розмірність/вимір Скаляр x: 0
Форма Скаляр x:  ()
Кількість елементів х: 1
-=--=--=--=--=--=--=--=--=--=-
Розглядаємо приклад з Вектор Рядок. 
Значення x буде: 
 [1 2 3]
Тип Вектор Рядок x:  <class 'numpy.ndarray'>
Розмірність/вимір Вектор Рядок x: 1
Форма Вектор Рядок x:  (3,)
Кількість елементів х: 3
-=--=--=--=--=--=--=--=--=--=-
Розглядаємо приклад з Вектор Стовпець. 
Значення x буде: 
 [[1]
 [2]
 [3]]
Тип Вектор Стовпець x:  <class 'numpy.ndarray'>
Розмірність/вимір Вектор Стовпець x: 2
Форма Вектор Стовпець x:  (3, 1)
Кількість елементів х: 3
-=--=--=--=--=--=--=--=--=--=-
Розглядаємо приклад з Матриця. 
Значення x буде: 
 [[1 2]
 [3 4]
 [5 6]]
Тип Матриця x:  <class 'numpy.ndarray'>
Розмірність/вимір Матриця x: 2
Форма Матриця x:  (3, 2)
Кількість елементів х: 6
-=--=--=--=--=--=--=--=--=--=-
Розглядаємо приклад з Багатовимірна Матриця. 
Значення x буде: 
 [[[111 112]
  [121 122]]

 [[211 

### Багатовимірні масиви, розуміння вимірів

>`Метод np.shape дозволяє зрозуміти виріми масиву і подає їх як (кількість рядків, кількість стовпців, кількість елементів).`

In [13]:
examples = {
    '5 рядків': np.array([[1], [2], [3], [4], [5]]), 
    '5 стовпців': np.array([[1, 2, 3, 4, 5]]),
    '5 елементів': np.array([[[1, 2, 3, 4, 5]]])
    }
for a in examples:
    print(f"Для {a} маємо shape: \n{examples[a].shape} \nта вигляд: \n{examples[a]}")

homework(f"Створіть власні масиви з різною кількістю елементів та використайте метод shape для визначення їх вимірів.")

import numpy as np

a = np.array([1, 2, 3])
print(f"Масив '1' має вигляд : {a.shape}")  

b = np.array([[1], [2], [3]])
print(f"Масив '2' має вигляд : {b.shape}")  

c = np.array([[1, 2], [3, 4], [5, 6]])
print(f"Масив '3' має вигляд : {c.shape}")  

d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(f"Масив '4' має вигляд : {d.shape}")  


Для 5 рядків маємо shape: 
(5, 1) 
та вигляд: 
[[1]
 [2]
 [3]
 [4]
 [5]]
Для 5 стовпців маємо shape: 
(1, 5) 
та вигляд: 
[[1 2 3 4 5]]
Для 5 елементів маємо shape: 
(1, 1, 5) 
та вигляд: 
[[[1 2 3 4 5]]]

>>>>> Створіть власні масиви з різною кількістю елементів та використайте метод shape для визначення їх вимірів. 

Масив '1' має вигляд : (3,)
Масив '2' має вигляд : (3, 1)
Масив '3' має вигляд : (3, 2)
Масив '4' має вигляд : (2, 2, 2)


### Indexing and Slicing

>`для доступу до елементів масиву використовуються Indexing, а якщо потрібно доступитись до декількох елементів зразу Slicing.`

In [ ]:
F = np.array([1, 1, 2, 3, 5, 8, 13, 21])
print(f"""Масив: {F}
Виміри: {F.shape}
Памятаємо, що номерація масивів відбувається з 0.
Тому перший елемент масиву:\n {F[0]}
Другий:\n {F[1]}
Останній, {len(F)}: \n {F[7]}""")

print(f"""Можемо скористатись відємними індексами якщо хочемо доступитись до елементів з кінця масиву.
Але номерація вже з 1.
Тому останній елемент:\n {F[-1]}
Передостанній:\n {F[-2]}""")

homework("Попрактикуйтесь доступатись до елементів, виведіть декілька елементів різними способами.")

--------

In [14]:
A = np.array([ [3.4, 8.7, 9.9], 
               [1.1, -7.8, -0.7],
               [4.1, 12.3, 4.8],
               [7.0, -3.9, 5.1]])

print(f"""Масив:
{A}
Виміри: {A.shape}
Принцип номерації такий самий, ТІЛЬКИ:
Якщо задати одне значення то візьметься цілий рядок:
    Перший рядок: {A[0]}
    Останній рядок: {A[-1]}
Для того щоб взяти цілий стовпець (символ : вказує взяти всі елементи): 
    Перший стовпець: {A[:,0]}
    Останній стовпець: {A[:,-1]}
Потрібно задавати два значення для отримання конкретного елемента: 
    Перший елемент: {A[0][0]} або {A[0, 0]}
    Останній елемент: {A[3][2]} або {A[-1][-1]} або {A[3, -1]}
""")

homework("Попрактикуйтесь в доступі до багатовимірного масиву, виведіть елементів які належать діагоналі.")

diagonal = A[::A.shape[1]+1]
print("Елементи, які належать діагоналі:")
for i in range(diagonal.shape[0]):
    print(diagonal[i,i])

Масив:
[[ 3.4  8.7  9.9]
 [ 1.1 -7.8 -0.7]
 [ 4.1 12.3  4.8]
 [ 7.  -3.9  5.1]]
Виміри: (4, 3)
Принцип номерації такий самий, ТІЛЬКИ:
Якщо задати одне значення то візьметься цілий рядок:
    Перший рядок: [3.4 8.7 9.9]
    Останній рядок: [ 7.  -3.9  5.1]
Для того щоб взяти цілий стовпець (символ : вказує взяти всі елементи): 
    Перший стовпець: [3.4 1.1 4.1 7. ]
    Останній стовпець: [ 9.9 -0.7  4.8  5.1]
Потрібно задавати два значення для отримання конкретного елемента: 
    Перший елемент: 3.4 або 3.4
    Останній елемент: 5.1 або 5.1 або 5.1


>>>>> Попрактикуйтесь в доступі до багатовимірного масиву, виведіть елементів які належать діагоналі. 

Елементи, які належать діагоналі:
3.4


>`Для доступу до декількох елементів використовують Slicing.`

In [15]:
S = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

print(f"""Масив:
{S}
Виміри: {S.shape}
Беремо декілька елементів: {S[2:5]}
Всі елементи до заданого: {S[:4]}
Всі елементи від заданого до кінця: {S[6:]}
Всі елементи: {S[:]}
""")
homework("Попрактикуйтесь у витягуванні елементів, візьміть 4 значення з кінця масиву.")

S[-4:]

A_upper = A[0:2, 0:2]
A_lower = A[3:5, 3:5]

Масив:
[0 1 2 3 4 5 6 7 8 9]
Виміри: (10,)
Беремо декілька елементів: [2 3 4]
Всі елементи до заданого: [0 1 2 3]
Всі елементи від заданого до кінця: [6 7 8 9]
Всі елементи: [0 1 2 3 4 5 6 7 8 9]


>>>>> Попрактикуйтесь у витягуванні елементів, візьміть 4 значення з кінця масиву. 



>`Такий самий принцип Slicing може використовуватись для багатовимірних масивів.`

In [16]:
A = np.array([
[11, 12, 13, 14, 15],
[21, 22, 23, 24, 25],
[31, 32, 33, 34, 35],
[41, 42, 43, 44, 45],
[51, 52, 53, 54, 55]])

print(f"""Масив:
{A}
Виміри: {A.shape}
Беремо декілька рядків: 
{A[0:2]}
Два перші стовпці: 
{A[:, 0:2]}
Два останні рядки:
{A[3:, :]}
Беремо підматрицю (нижні елементи): 
{A[-3:, -3:]}
""")
homework("Попрактикуйтесь у витягуванні елементів, візьміть матрицю 2х2 з нижнього та верхнього кутка матриці А.")

print("Матриця 2x2 з верхнього кутка матриці A:")
print(A_upper)

print("Матриця 2x2 з нижнього кутка матриці A:")
print(A_lower)


Масив:
[[11 12 13 14 15]
 [21 22 23 24 25]
 [31 32 33 34 35]
 [41 42 43 44 45]
 [51 52 53 54 55]]
Виміри: (5, 5)
Беремо декілька рядків: 
[[11 12 13 14 15]
 [21 22 23 24 25]]
Два перші стовпці: 
[[11 12]
 [21 22]
 [31 32]
 [41 42]
 [51 52]]
Два останні рядки:
[[41 42 43 44 45]
 [51 52 53 54 55]]
Беремо підматрицю (нижні елементи): 
[[33 34 35]
 [43 44 45]
 [53 54 55]]


>>>>> Попрактикуйтесь у витягуванні елементів, візьміть матрицю 2х2 з нижнього та верхнього кутка матриці А. 

Матриця 2x2 з верхнього кутка матриці A:
[[ 3.4  8.7]
 [ 1.1 -7.8]]
Матриця 2x2 з нижнього кутка матриці A:
[]


>`Slicing дозволяє брати не тільки послідовні значення але із заданим кроком.`

In [17]:
A = np.arange(28).reshape(4, 7)

print(f"""Масив:
{A}
Виміри: {A.shape}
Беремо кожен дугий елемент першого рядка: 
{A[0, ::2]}
Беремо кожен третій елемент першого рядка: 
{A[0, ::3]}
Кожен другий елемент в кожномуу другому рядку: 
{A[::2, ::2]}
Останні три елементи в кожному другому рядку:
{A[::2, 4:]}
Можна повнісню змінити порядок елементів (дзерально обернемо):
{A[::-1, ::-1]}
""")

homework("Попрактикуйтесь у витягуванні елементів, будь-яка робоча комбінація.")

A[:, -1]

Масив:
[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]]
Виміри: (4, 7)
Беремо кожен дугий елемент першого рядка: 
[0 2 4 6]
Беремо кожен третій елемент першого рядка: 
[0 3 6]
Кожен другий елемент в кожномуу другому рядку: 
[[ 0  2  4  6]
 [14 16 18 20]]
Останні три елементи в кожному другому рядку:
[[ 4  5  6]
 [18 19 20]]
Можна повнісню змінити порядок елементів (дзерально обернемо):
[[27 26 25 24 23 22 21]
 [20 19 18 17 16 15 14]
 [13 12 11 10  9  8  7]
 [ 6  5  4  3  2  1  0]]


>>>>> Попрактикуйтесь у витягуванні елементів, будь-яка робоча комбінація. 



array([ 6, 13, 20, 27])

>`можна здійснювати вибірку елементів по умові`

In [18]:
A = np.arange(50)
all_even = (A%2==0) # парні
complex = (A<30) & (A/5<2) 

print(f"""Спочатку потрібно створити умову за якою здійснювати вибірку.
Результат умови буде або {all_even[0]} для {A[0]} або {all_even[1]} для {A[1]}.
Після підставляння умови пошуку парних чисел в масив отримаємо:
{A[all_even]}
Або застосувавти більш комплексну умову з двох порінянь:
{A[complex]}""")

homework("Виведіть всі непарні числа з даного масиву.")

A = np.arange(50)
odd_numbers = A[A%2==1]
print(f"Непарні числа: {odd_numbers}")

Спочатку потрібно створити умову за якою здійснювати вибірку.
Результат умови буде або True для 0 або False для 1.
Після підставляння умови пошуку парних чисел в масив отримаємо:
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48]
Або застосувавти більш комплексну умову з двох порінянь:
[0 1 2 3 4 5 6 7 8 9]

>>>>> Виведіть всі непарні числа з даного масиву. 

Непарні числа: [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]


### Функції для створення матриць: ones, zeros, identity, eye, empty

In [19]:
o = np.ones(5)
z = np.zeros(5)
i = np.identity(5)
e = np.eye(5)
t = np.empty(5)

print(f"""
Всі елементи 1:
{o}
Всі елементи 0:
{z}
Матриця в якої діагональ всі 1:
{i}
Також, діагональ всі 1 (зменшимо вивід):
{e[:2, :2]}
Пуста матриця буде містити набір випадкових чисел які записані у память де був ініціалізований масив:
{t}
""")


Всі елементи 1:
[1. 1. 1. 1. 1.]
Всі елементи 0:
[0. 0. 0. 0. 0.]
Матриця в якої діагональ всі 1:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Також, діагональ всі 1 (зменшимо вивід):
[[1. 0.]
 [0. 1.]]
Пуста матриця буде містити набір випадкових чисел які записані у память де був ініціалізований масив:
[ 1.   19.75 38.5  57.25 76.  ]

